import os

DEPLOYMENT_SERVER = os.getenv('DEPLOYMENT_SERVER')
MONGO_HOST = os.getenv('MONGO_HOST')
MONGO_PORT = os.getenv('MONGO_PORT')
MONGO_USER = os.getenv('MONGO_USER')
MONGO_PASS = os.getenv('MONGO_PASS')
MONGO_DB_NAME = os.getenv('MONGO_DB_NAME')
RESERVATION_BEFORE_AND_AFTER_TIME = os.getenv('RESERVATION_BEFORE_AND_AFTER_TIME')
